import 'package:flutter/material.dart';
import 'package:campuswhisper/core/theme/app_dimensions.dart';
import 'package:campuswhisper/models/posts_model.dart';
import 'package:campuswhisper/providers/user_provider.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:provider/provider.dart';

import '../../../widgets/custom_dropdown.dart';
import '../../../widgets/custom_input.dart';
import '../../../widgets/default_button.dart';

class AddPost extends StatefulWidget {
  final List<String> tags;
  final Function(PostModel) onPostCreated;
  final PostModel? existingPost; // For editing mode

  const AddPost({
    super.key,
    required this.tags,
    required this.onPostCreated,
    this.existingPost,
  });

  @override
  State<AddPost> createState() => _AddPostState();
}

class _AddPostState extends State<AddPost> {
  final TextEditingController _contentController = TextEditingController();
  String? _selectedTag;
  final bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    // If editing, prefill the fields
    if (widget.existingPost != null) {
      _contentController.text = widget.existingPost!.content;
      _selectedTag = _getDisplayTag(widget.existingPost!.type);
    }
  }

  @override
  void dispose() {
    _contentController.dispose();
    super.dispose();
  }

  // Map database types to display tags
  String _getDisplayTag(String postType) {
    switch (postType) {
      case 'question':
        return 'Questions';
      case 'discussion':
        return 'Discussions';
      case 'announcement':
        return 'Announcements';
      default:
        return postType;
    }
  }

  // Map display tags to database types
  String _getPostType(String displayTag) {
    switch (displayTag) {
      case 'Questions':
        return 'question';
      case 'Discussions':
        return 'discussion';
      case 'Announcements':
        return 'announcement';
      default:
        return displayTag.toLowerCase();
    }
  }

  void _handleSubmit() {
    if (_contentController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter post content')),
      );
      return;
    }

    if (_selectedTag == null) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Please select a tag')));
      return;
    }

    // Get current user
    final currentUser = FirebaseAuth.instance.currentUser;
    if (currentUser == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('You must be logged in to create a post')),
      );
      return;
    }

    // Get user name from UserProvider
    final userProvider = context.read<UserProvider>();
    final userName = userProvider.currentUser != null
        ? '${userProvider.currentUser!.firstName} ${userProvider.currentUser!.lastName}'
        : currentUser.displayName ?? 'Anonymous';

    // Create or update post model
    final PostModel post;

    if (widget.existingPost != null) {
      // Update existing post
      post = PostModel(
        postId: widget.existingPost!.postId,
        type: _getPostType(_selectedTag!),
        createdBy: widget.existingPost!.createdBy,
        createdByName: widget.existingPost!.createdByName,
        content: _contentController.text.trim(),
        createdAt: widget.existingPost!.createdAt,
        upvoteCount: widget.existingPost!.upvoteCount,
        downvoteCount: widget.existingPost!.downvoteCount,
        commentCount: widget.existingPost!.commentCount,
        updatedAt: DateTime.now(),
        courseId: widget.existingPost!.courseId,
        title: widget.existingPost!.title,
      );
    } else {
      // Create new post
      post = PostModel(
        postId: '', // Will be generated by Firestore
        type: _getPostType(_selectedTag!),
        createdBy: currentUser.uid,
        createdByName: userName,
        content: _contentController.text.trim(),
        createdAt: DateTime.now(),
        upvoteCount: 0,
        downvoteCount: 0,
      );
    }

    widget.onPostCreated(post);
    Navigator.of(context).pop();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        CustomInput(
          controller: _contentController,
          fieldLabel: 'What\'s on your mind?',
          hintText: 'Share your thoughts with the campus...',
          validation: false,
          errorMessage: '',
          maxLines: 5,
          minLines: 3,
          autofocus: false,
          textInputAction: TextInputAction.newline,
          inputType: TextInputType.multiline,
        ),
        AppDimensions.h16,
        CustomDropdown<String>(
          fieldLabel: 'Select Tag',
          hintText: 'Choose a category',
          validation: true,
          errorMessage: 'Please select a tag',

          items: widget.tags
              .map((tag) => DropdownItem(value: tag, text: tag))
              .toList(),
          selectedValue: _selectedTag,
          onChanged: (value) {
            setState(() {
              _selectedTag = value;
            });
          },
        ),
        AppDimensions.h24,
        DefaultButton(
          text: widget.existingPost != null ? 'Update' : 'Post',
          press: _handleSubmit,
          isLoading: _isLoading,
        ),
      ],
    );
  }
}
